server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/cfuvsched
    username: schedadmin
    password: schedadmin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        id:
          new_generator_mappings: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  sql:
    init:
      mode: always

connector:
  auth:
    url: ${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8081}/auth
