server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cfuvsched
    username: schedadmin
    password: schedadmin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        id:
          new_generator_mappings: true
  jackson:
    serialization:
      fail-on-empty-beans: false

connector:
  auth:
    url: localhost:8081/auth