version: '3.5'

services:
  postgres:
    container_name: cfuvsched
    image: postgres
    environment:
      POSTGRES_DB: cfuvsched
      POSTGRES_USER: schedadmin
      POSTGRES_PASSWORD: schedadmin
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
