server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/cfuvsched
    username: schedadmin
    password: schedadmin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

connector:
  auth:
    url: localhost:8081/auth