server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cfuvsched
    username: schedadmin
    password: schedadmin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update