pipeline {
  agent any

  environment {
    mavenHome = tool 'jenkins-maven'
  }

  stages {
    stage('Run unit tests') {
      steps{
        sh 'cd server && mvn -pl auth -am clean test -P unit'
      }
    }
    stage('Run integration tests') {
      steps{
        sh 'cd server && mvn -pl auth -am clean test -P integration'
      }
    }
    stage('Build project') {
      steps{
        sh 'cd server && mvn -pl auth -am clean package -Dmaven.test.skip=true'
      }
    }
    stage('Build docker image') {
      steps{
        sh 'cd server/auth && ls && ls target && docker build -f Dockerfile -t cfuvscheduling_auth:test .'
      }
    }
    stage('Run application') {
      steps{
        catchError{
          sh 'docker stop cfuvscheduling_auth'
        }
        catchError{
          sh 'docker container rm cfuvscheduling_auth'
        }
        sh """docker run -d --name=cfuvscheduling_auth -p 8081:8081 --network=cfuvsched_net -e POSTGRES_HOST=${env.POSTGRES_HOST} cfuvscheduling_auth:test"""
      }
    }
  }
}