server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/cfuvsched
    username: schedadmin
    password: schedadmin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          id:
            new_generator_mappings: true
            jwt:
              secret: your-secret-key
              expiration: 3600
  sql:
    init:
      mode: always
