name: Check project stability and running tests before merging to master
run-name: Build project and run tests
on:
  pull_request:
    branches:
      - 'master'
jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build authorization module
        run: cd ./server && mvn -pl auth -am clean package -Dmaven.test.skip=true
      - name: Build admin module
        run: cd ./server && mvn -pl admin -am clean package -Dmaven.test.skip=true
      - name: Build timetable manager module
        run: cd ./server && mvn -pl tt-manager -am clean package -Dmaven.test.skip=true

  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run unit tests on authorization module
        run: cd ./server && mvn -pl auth -am clean test -P unit
      - name: Run unit tests on admin module
        run: cd ./server && mvn -pl admin -am clean test -P unit
      - name: Run unit tests on timetable manager module
        run: cd ./server && mvn -pl tt-manager -am clean test -P unit
  integration_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run integration tests on authorization module
        run: cd ./server && mvn -pl auth -am clean test -P integration
      - name: Run integration tests on admin module
        run: cd ./server && mvn -pl admin -am clean test -P integration
      - name: Run integration tests on timetable manager module
        run: cd ./server && mvn -pl tt-manager -am clean test -P integration
